import Head from "next/head";
import { CalculatorApp } from "../src/components/CalculatorApp";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          padding: "24px",
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          backgroundColor:"#CB9CF2"
        }}
      >
        <CalculatorApp />
      </main>
    </div>
  );
}
